title: Keith Taylor's Jekyll Training
author: Keith Taylor
email: keechatay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Is Jekyll a good alternative to WordPress for blogs? WordPress has 
  dominated Content Management Systems (CMS) for years. But what if you just want to blog?
  Let's see if GitHub pages with Jekyll is better than WordPress (or Ghost) as a blogging platform.

# social links
twitter_username: KeithTaylor
github_username:  KeithCharlieTaylor

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
